# Generated by Django 3.1 on 2021-08-20 09:26

from django.db import migrations, models
import django.db.models.deletion
import tryon.models.models
import tryon.models.product
import tryon.models.productnb
import tryon.models.tryon
from tryon.models.models import get_file_path


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True,
                 help_text='데이터가 생성된 날짜입니다.', verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True,
                 help_text='데이터가 수정된 날짜입니다.', verbose_name='수정 일시')),
                ('gender', models.CharField(choices=[
                 ('M', 'Male'), ('F', 'Female')], default='F', max_length=1)),
                ('image', models.ImageField(
                    upload_to=get_file_path)),
            ],
            options={
                'verbose_name': 'Image_models',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True,
                 help_text='데이터가 생성된 날짜입니다.', verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True,
                 help_text='데이터가 수정된 날짜입니다.', verbose_name='수정 일시')),
                ('gender', models.CharField(choices=[
                 ('M', 'Male'), ('F', 'Female')], default='F', max_length=1)),
                ('part', models.CharField(choices=[('상의', 'Top'), ('하의', 'Bottom'), (
                    '아우터', 'Outer'), ('원피스', 'Dress')], default='하의', max_length=3)),
                ('image', models.ImageField(
                    upload_to=tryon.models.product.get_file_path)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemplatePage',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True,
                 help_text='데이터가 생성된 날짜입니다.', verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True,
                 help_text='데이터가 수정된 날짜입니다.', verbose_name='수정 일시')),
                ('part', models.CharField(choices=[('상의', 'Top'), ('하의', 'Bottom'), (
                    '아우터', 'Outer'), ('원피스', 'Dress')], default='하의', max_length=3)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=200)),
                ('single_line', models.TextField()),
                ('grid', models.TextField()),
                ('zigzag', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TryOnImage',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True,
                 help_text='데이터가 생성된 날짜입니다.', verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True,
                 help_text='데이터가 수정된 날짜입니다.', verbose_name='수정 일시')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True,
                 help_text='CDN IMG', max_length=500)),
                ('image', models.ImageField(
                    upload_to=tryon.models.tryon.get_file_path)),
                ('default', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductNB',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True,
                 help_text='데이터가 생성된 날짜입니다.', verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True,
                 help_text='데이터가 수정된 날짜입니다.', verbose_name='수정 일시')),
                ('part', models.CharField(choices=[('상의', 'Top'), ('하의', 'Bottom'), (
                    '아우터', 'Outer'), ('원피스', 'Dress')], default='하의', max_length=3)),
                ('url', models.CharField(blank=True,
                 help_text='CDN IMG', max_length=500)),
                ('image', models.ImageField(
                    upload_to=tryon.models.productnb.get_file_path)),
                ('title', models.CharField(max_length=200)),
                ('product', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='tryon.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
