# Generated by Django 3.1 on 2021-08-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='models',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
