# Generated by Django 3.1 on 2021-08-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryon', '0002_models_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=1),
        ),
    ]
