# Generated by Django 3.1 on 2021-08-18 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tryon', '0004_product_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tryonimage',
            name='template',
        ),
    ]
