# Generated by Django 3.1 on 2021-08-19 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryon', '0005_remove_tryonimage_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='tryonimage',
            name='url',
            field=models.CharField(blank=True, help_text='CDN IMG', max_length=500),
        ),
    ]
