# Generated by Django 3.1 on 2021-08-19 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryon', '0006_tryonimage_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='productnb',
            name='url',
            field=models.CharField(blank=True, help_text='CDN IMG', max_length=500),
        ),
    ]
